name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build + Test Stable
    runs-on: ubuntu-latest
    steps:

    - name: Build
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get Coverage
      run:  go get golang.org/x/tools/cmd/cover

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic

    - name: Coverage
      run: bash <(curl -s https://codecov.io/bash)

  build-legacy:
    name: Build + Test Previous Stable
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.14', '1.13', '1.12']
    steps:

    - name: Build ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test ./... 
