name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build + Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15', '1.14', '1.13', '1.12', '1.11', '1.10', '1.9', '1.8', '1.7']
    steps:

    - name: Build ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
