name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build + Test Stable
    runs-on: ubuntu-latest
    env:
      GO111MODULE: auto
    steps:

    - name: Build
      uses: actions/setup-go@v2
      with:
        go-version: '1.x'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get Coverage
      run:  go get golang.org/x/tools/cmd/cover

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic

    - name: Coverage
      uses: codecov/codecov-action@v2

  build-legacy:
    name: Build + Test Previous Stable
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.16.x', '1.15.x', '1.14.x']
    steps:

    - name: Build ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test ./... 
